# Generated by Django 2.0.7 on 2019-03-12 10:58

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import transporter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company_address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=transporter.models.Transporter.meta_default)),
                ('transporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transporters',
            },
        ),
    ]
