# Generated by Django 2.0.1 on 2018-03-20 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(db_index=True, max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(db_index=True, max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
