# Generated by Django 2.0.1 on 2018-01-11 17:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import fleet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('hub', models.CharField(max_length=15)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=fleet.models.CommissionAgent.meta_default)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('truck_number', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('fleet_type', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('age', models.DateField()),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=fleet.models.Fleet.meta_default)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FleetOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=fleet.models.FleetOwner.meta_default)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fleet',
            name='fleet_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.FleetOwner'),
        ),
    ]
