# Generated by Django 2.0.1 on 2018-01-15 09:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import fleet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('hub', models.CharField(max_length=15)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=fleet.models.CommissionAgent.meta_default)),
            ],
            options={
                'verbose_name_plural': 'Commission Agents',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.City')),
            ],
            options={
                'verbose_name_plural': 'Feeds',
            },
        ),
        migrations.CreateModel(
            name='FleetOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=fleet.models.FleetOwner.meta_default)),
            ],
            options={
                'verbose_name_plural': 'Fleet Owners',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('commission_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.CommissionAgent')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='common.City')),
                ('fleet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.FleetOwner')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='common.City')),
            ],
            options={
                'verbose_name_plural': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('chasis_number', models.CharField(max_length=255)),
                ('engine_number', models.CharField(max_length=255)),
                ('body_type', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(choices=[('Deisel', 'Deisel'), ('Petrol', 'Petrol')], max_length=100)),
                ('color', models.CharField(max_length=255)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=fleet.models.Vehicle.meta_default)),
                ('fleet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.FleetOwner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='feed',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.Vehicle'),
        ),
    ]
