# Generated by Django 2.0.1 on 2018-03-05 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('agent', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('departure_date', models.DateField()),
                ('material_to_carried', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=20)),
                ('commission_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.CommissionAgent')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_destination', to='common.City')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_source', to='common.City')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.Vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.CharField(max_length=100)),
                ('etd', models.CharField(max_length=255, verbose_name='Estimated time of Delivery')),
                ('commission_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.CommissionAgent')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.Lead')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.Vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('rated_entity', models.PositiveSmallIntegerField(choices=[(1, 'Commission Agent'), (2, 'Fleet Owner')])),
                ('rating', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.Job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='job',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.Quote'),
        ),
    ]
