# Generated by Django 2.0.1 on 2018-03-28 06:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=fleet.models.VehicleType.meta_default),
        ),
    ]
