# Generated by Django 2.0.1 on 2018-03-05 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0002_auto_20180305_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleetowner',
            name='name',
        ),
        migrations.AddField(
            model_name='fleetowner',
            name='fleet_owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
