# Generated by Django 2.0.1 on 2018-04-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_auto_20180330_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobstatus',
            options={'verbose_name_plural': 'Job Status'},
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='length',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='weight',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
