# Generated by Django 2.0.1 on 2018-05-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_auto_20180408_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='etd',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='Estimated time of Delivery(Hrs)'),
        ),
    ]
