# Generated by Django 2.0.1 on 2018-05-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_auto_20180507_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='weight',
            field=models.FloatField(db_index=True, max_length=255, verbose_name='Weight(Ton)'),
        ),
    ]
