# Generated by Django 2.0.7 on 2018-07-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_auto_20180713_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='fleet_owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agent.CommissionAgent'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fleet_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.CommissionAgent'),
        ),
    ]
