# Generated by Django 2.0.7 on 2018-07-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_auto_20180724_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvehicle',
            old_name='fleet_owner',
            new_name='commission_agent',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='fleet_owner',
            new_name='commission_agent',
        ),
    ]
