# Generated by Django 2.0.7 on 2019-03-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0001_initial'),
        ('fleet', '0010_auto_20180725_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transporter.Transporter'),
        ),
        migrations.AddField(
            model_name='quote',
            name='fleet_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.FleetOwner'),
        ),
    ]
