# Generated by Django 2.0.1 on 2018-01-15 10:59

import agent.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=None, max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('hub', models.CharField(max_length=15)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(default=agent.models.CommissionAgent.meta_default)),
            ],
            options={
                'verbose_name_plural': 'Commission Agents',
            },
        ),
    ]
