# Generated by Django 2.0.1 on 2018-03-05 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionagent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commissionagent',
            name='name',
        ),
        migrations.AddField(
            model_name='commissionagent',
            name='agent',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
