# Generated by Django 2.0.1 on 2018-03-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20180330_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissionagent',
            old_name='company_data',
            new_name='company_address',
        ),
        migrations.AddField(
            model_name='commissionagent',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
