# Generated by Django 2.0.1 on 2018-06-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('agent', '0003_auto_20180330_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionagent',
            name='hub',
        ),
        migrations.AddField(
            model_name='commissionagent',
            name='hub',
            field=models.ManyToManyField(blank=True, db_index=True, to='common.State'),
        ),
    ]
