# Generated by Django 2.0.7 on 2018-07-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_auto_20180615_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionagent',
            name='agent_type',
            field=models.CharField(blank=True, choices=[('CA', 'Commission Agent'), ('FO', 'Fleet Owner')], max_length=20, null=True),
        ),
    ]
